---
- hosts: all
  become: yes 
  tasks: 
  - name: i want to install tree
    apt:
      name: tree
      state: present

  - name: iwant to install wget
    apt:
      name: wget
      state: present
